### ISSUE TITLE
feature suggestion: user accounts

### ISSUE THREAD

**Issue by eloibahuet** [zachlevy/history-videos#3]
Hello，
I wasnt able to post a message using the website's form (I use Nightly)
I really love your website. I use it several times a week when stretching after a run.It is so handy that I seldom go directly to these youtube channels anymore.
For this reason I was wondering how feasible it would be for you to create some kind of an account system that would keep track of watched videos (and possibly notify when a new video is added) As of right now I always spend sometime scrolling trying to find a video I havent watched before..
If you decide to impliment such a feature I might be able to help even tho my web programming skils are to my forte.
In any case thanks again for this great website

**Comment by zachlevy** [comment]
hey eloib, thanks! 

i actually got your form submission, like 10 of them lol. i fixed the bug on the form so it should be pretty clear that someone's feedback was received now.

there's currently no database for the website, it just gets the battles from `moments.json`, so a user system would require adding a database and "ejecting" the create-react-app code to build a route in express. or creating a separate api server.

However, cookies would be a good solution I think for this. just store which videos you've watched in a cookie and then show a "rewatch" button or something like that. Not good if you clear your cookies or switch browsers of course.

Perhaps add a `uploaded` attribute to the `moment.json` objects and then show a "new" tag for videos that were uploaded within the past month?

how did you find out about the website?

**Comment by eloibahuet** [comment]
I read about the website on reddit, it was mentioned in a thread about a new video.

Unfortunately on second thoughts I don't think I can do any satisfactory work with Json as I have never touched JS or anthything it before, sorry! 
I have added one of my favorite video that was missing from the website in` moments.json` tho. Did you extract all the videos info using youtube api?

Let me know if there is any manageable task I could do to help. Unfortunately the extent of my programming experience so far have been college problem sets in C and python.. I'll make time to understand how you built this during this week end.

**Comment by zachlevy** [comment]
awesome thanks for adding the missing video! I thought about using the youtube api but because the lat/lng requires some human input, i figured I'd just do it all manually. so I just add them every time they come out.

Will do!

**Comment by zachlevy** [comment]
I've added a "new" video tag for videos that have come out with in the past 30 days.

**Comment by zachlevy** [comment]
I also added a lighter version of users using cookies as I mentioned before. @eloib thanks for the suggestions!
